baseURL: 'https://www.mauricioseixas.adv.br/'
languageCode: 'pt-br'
title: 'Maurício Seixas | Advogado Criminal'
enableRobotsTXT: true
defaultContentLanguage: 'pt-br'
module:
  disable: true

# Configurações para Sitemap
sitemap:
  changefreq: 'weekly'
  priority: 0.8

# Variáveis do Produto
params:
  logo: 'images/logo.png'
  whatsapp: 'images/whatsapp.png'
  lawyer: 'images/advogado.jpg'
  intro: 'Nosso objetivo é oferecer um atendimento humano e compassivo em casos criminais, proporcionando apoio técnico especializado. Além disso, estamos comprometidos em garantir uma resposta imediata em situações de urgência, a fim de proteger e cuidar das pessoas afetadas. Nossa luta incansável visa assegurar os direitos fundamentais de todos, promovendo justiça e igualdade em nossa sociedade.'
  subtitulo: 'Maurício Seixas'
  resumo1: ' é advogado criminalista comprometido com uma advocacia personalizada e de excelência. Formado pela PUCRS em 2007 e alia sua sólida formação acadêmica há 28 anos de experiência no Exército Brasileiro, onde desenvolveu valores fundamentais como ética, estratégia e confiança.'
  resumo2: 'Atualmente cursando especialização em Tribunal do Júri, está em constante aprimoramento para oferecer uma defesa técnica e comprometida. Sua abordagem artesanal garante máxima atenção a cada processo, com dedicação aos detalhes e foco em proteger os direitos e interesses de seus clientes.'
  description: 'Advogado criminal especializado em defesa criminal em Porto Alegre. Atuação em casos de crimes graves e defesa de clientes em tribunais.'
  disclaimer:
    [
      '- Delegacia, Flagrante e Custódia',
      '- Flagrantes 24 Horas',
      '- Defesa Criminal e Recursos',
      '- Habeas Corpus e Liberdade Provisória',
      '- Execução Penal',
      '- Tribunal do Júri',
    ]
  cta_texto: 'Entre em contato'
  cta_link: 'https://api.whatsapp.com/send?phone=5551994830348&text=Ol%C3%A1!%20Gostaria%20de%20conversar%20com%20um%20advogado.'
  footer_text: '© 2024 Maurício Seixas'
